Fetch cube
zazuko/barnard59 pull request #215
Opened 2023-11-24 17:16 UTC by giacomociti

renamed fetch-constraint and check-constraint to fetch-cube and check-cube

fetch-cube includes also the cbd of cube

2023-11-24 20:28 UTC, giacomociti commented
I'm thinking that maybe `fetch-metadata` and `check-metadata` would be better names, highlighting that a cube is made of observations (data) and metadata (including the constraint)

2023-11-27 09:55 UTC, tpluscode requested changes

2023-11-27 09:55 UTC, tpluscode commented on .changeset/unlucky-plants-carry.md
> +"barnard59-cube": major
I know it's technically a breaking change but no has had the chance to use this yet :)

```suggestion
"barnard59-cube": patch
```

2023-11-27 09:55 UTC, tpluscode commented on packages/cube/README.md
> +The following pipelines retrieve and validate cube observations and their metadata.
```suggestion
The following pipelines retrieve and validate cube observations and metadata.
```

2023-11-27 09:55 UTC, tpluscode commented on packages/cube/README.md
> +cat metadata.ttl \
```suggestion
cat cube.ttl \
```

2023-11-27 09:55 UTC, tpluscode commented on packages/cube/manifest.ttl
> +  rdfs:label "Retrieves cube and constraint from SPARQL endpoint" ;
```suggestion
  rdfs:label "Retrieves cube and its constraint shape from SPARQL endpoint" ;
```

2023-11-27 09:55 UTC, tpluscode commented on packages/cube/manifest.ttl
> +  rdfs:label "Validate input cube and constraint against profile shapes" ;
```suggestion
  rdfs:label "Validate input cube and its constraint against profile shapes" ;
```

2023-11-27 11:57 UTC, tpluscode approved these changes

2023-11-27 12:14 UTC, merged