More cube fetch
zazuko/barnard59 pull request #263
Opened 2024-01-18 11:33 UTC by giacomociti

2024-01-19 12:22 UTC, tpluscode requested changes

2024-01-19 12:22 UTC, tpluscode commented on packages/cube/lib/report.js
> +import rdf from 'barnard59-env'
Please avoid using this directly and get from `this.env` in the step factory

2024-01-19 12:22 UTC, tpluscode commented on packages/cube/package.json
> +    "barnard59-env": "^1.2.0",
And then move back to dev deps

2024-01-19 12:22 UTC, tpluscode commented on packages/cube/manifest.ttl
> +.
I though this belonged to the `b59-shacl` package. Then adding dependency on `rdf-validate-shacl` would not be necessary in this `b59-cube`

2024-01-22 09:25 UTC, giacomociti commented on packages/cube/lib/report.js
> +import rdf from 'barnard59-env'
done, I was not aware that [`base:map`](https://github.com/zazuko/barnard59/blob/2c64f4da790ceab0b4dd1795a81e55de4cfdacc6/packages/base/map.js#L45) is smart enough to inject the context

2024-01-22 11:25 UTC, tpluscode commented on packages/cube/lib/report.js
> +import rdf from 'barnard59-env'
Yes, we added that a some point so that you can access variables

2024-01-22 11:34 UTC, tpluscode approved these changes
I took the liberty of adding a second changeset

2024-01-22 12:38 UTC, merged